sudo: required
language: c

os:
  - linux

install:
  - sudo apt-get install -y pandoc

script:
  - make epub
  - make html
  - make release

deploy:
  provider: releases
  api_key: $GH_OATH_TOKEN
  file:
    - swebok-ru.epub
    - swebok-ru.zip
  skip_cleanup: true
