sudo: required
language: ruby

rvm:
  - 2.2

os:
  - linux

before_script:
  - gem install awesome_bot
  - sudo apt-get install -y pandoc

script:
  - make epub
  - make html
  - make release
  - awesome_bot README.md *.markdown --allow-redirect --allow-ssl --allow-dupe --white-list https://ru.linkedin.com/in/yurybuluy,https://www.linkedin.com/in/sorlik

deploy:
  provider: releases
  api_key: $GH_OATH_TOKEN
  file:
    - "swebok-ru.epub"
    - "swebok-ru.zip"
  on:
    branch: master

notifications:
  email:
    recipients:
      - estetus+travis-ci@gmail.com
    on_success: change
    on_failure: always
